### ISSUE TITLE
Crash on picking up Tomatoes

### ISSUE THREAD

**Issue by TheNimbleNinja** [DawnTeamMC/Culinaire#10]
https://gist.githubusercontent.com/natanfudge/2fb66a7d8405d610b912b7247954601e/raw/b6ad86bca4cd4f7fcfbbb8b8be0d9cae6e8c2aa5/crash.txt

**Comment by Hugman76** [comment]
You are using another mod that uses a vanilla method in the wrong way. Some mod is trying to place a tomato from an item to a crop. Any idea what mod that could be? You are using way too many mods for me to even be able to find which one is causing it.

**Comment by TheNimbleNinja** [comment]
i have no idea wat mod could cause it. it happens on a structure generating and breaking your crops
