### ISSUE TITLE
Milk Suggestion

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [DawnTeamMC/Culinaire#14]
toogleable option, available through mod menu or config file, configuring how much can bottles of milk stack, would be very appreciated 🥺 from unstackable to 16 bottles in slot I suppose. With 4/8 and maybe other numbers available?

it makes sense when run with mods altering potion and potion stucking, but somehow they have no effect over milk bottles from Culinaire. I will post versions and names later this day.

even tho i still dont think its a mere compitability issue and would appreciate, as many more users, to have it as independant native for mod option

**Comment by YanisBft** [comment]
Note that if implemented, such an option would require a server restart or a single world disconnect/reconnect

**Comment by TheSunIsADeadlyLaser** [comment]
> Note that if implemented, such an option would require a server restart or a single world disconnect/reconnect

worth it imo
