### ISSUE TITLE
Crash involving Tomatoes

### ISSUE THREAD

**Issue by Cookie-Kurokami** [DawnTeamMC/Culinaire#16]
I cannot even rejoin my server without this crash immediately re-occurring and shutting the whole thing down, presumably because there's something wrong with a so-called "TomatoesBlock" near my location.
[crash-2021-08-10_03.25.55-server.txt](https://github.com/DawnTeamMC/Culinaire/files/6958755/crash-2021-08-10_03.25.55-server.txt)

**Comment by Hugman76** [comment]
Cannot reproduce.

**Comment by Hugman76** [comment]
Same as #10 actually
