### ISSUE TITLE
Can't drink milk from bucket

### ISSUE THREAD

**Issue by Laifsyn** [DawnTeamMC/Culinaire#37]
![image](https://user-images.githubusercontent.com/99366187/159640836-cca54f53-8a48-4bdd-8e39-66cab559bd36.png)
Mod lists.
Fabric Loader 0.13.3
MC 1.18.1
Is it possible to fix it with a datapack, or do I have to wait for update?

**Comment by Hugman76** [comment]
Within .minecraft/config, or through Mod Menu you can toggle this on and off by yourself.

**Comment by Laifsyn** [comment]
That legit is way too out of vanilla why defaulted to disabled? XD

**Comment by Laifsyn** [comment]
unless I've disabled it. which would be my bad then

**Comment by Hugman76** [comment]
It's disabled by default because we've added milk bottles, and since there are both water bottle and water buckets and that you can't drink water buckets, it makes sense that you don't want to drink from milk buckets + you would drink 3 times a milk bottle.

**Comment by Laifsyn** [comment]
That.. makes sense. I would've never found out about the bucket weren't because of Dehydrated though(It satiates dehydration the fastest)
