### ISSUE TITLE
com.hugman.culinaire.util.RecipeSerializerUtil not committed

### ISSUE THREAD

**Issue by tambry** [DawnTeamMC/Culinaire#42]
### What happened?

I'm upgrading the mod to 1.19 for my own purposes, but unfortunately the `com.hugman.culinaire.util.RecipeSerializerUtil` class used since commit c1df78f0213b6f1c37ca966b42c59e75fd5549a4 seems to have not been committed to the repository.

Any chance it could be published?  
I can guess at what `ingredientListOrObject()` does, but reverse engineering it into existence seems pointless. 🙂 

### Dawn API version

dev

### Fabric API version

0.56.0+1.19

**Comment by Hugman76** [comment]
Okay I might have actually done a weird thing and uploaded it to an another branch https://github.com/DawnTeamMC/Culinaire/blob/55c42297df614d56f268915ade191cb3504f32a0/src/main/java/com/hugman/culinaire/util/RecipeSerializerUtil.java

**Comment by Hugman76** [comment]
Just letting you know; I'll be updating all of the mods to 1.19 in a week or so 😀 but I'm really happy to see you be that interested in Culinaire!
