### ISSUE TITLE
Tomatoes mess up when Right-Click harvested

### ISSUE THREAD

**Issue by IdrisQe** [DawnTeamMC/Culinaire#9]
When using the right-click-to-harvest functionality from _TinyTweaks_, Tomatoes only break/replant half of the block, leaving half floating, and can also "replant" in the air. I don't know if this is an issue with how TinyTweaks implements its harvest functionality, or an issue with how CE:F implements the two-high crop.

![gif](https://user-images.githubusercontent.com/40530630/111058569-5abe5e00-8444-11eb-8504-4e19daa284b7.gif)

Made an issue there too. Will try to keep up-to-date on both, and will close if it's solved on either side.
https://github.com/Haven-King/TinyTweaks/issues/69

**Comment by Hugman76** [comment]
Tell me if it still occurs in v1.1.4 (when it will be up).

**Comment by IdrisQe** [comment]
Unfortunately it's only partially fixed. When the top half is harvested, the entire crop does break as intended now (though doesn't get replanted- this part would need to be implemented on TinyTweaks end I imagine) but the issue still occurs when the bottom half is harvested instead.
